### ISSUE TITLE
Use Postman Public Workspace for API docs and collections

### ISSUE THREAD

**Issue by pankajk07** [binance/binance-api-postman#75]
Postman recently launced Public Workspaces, with loads of features. Binance can leverage it to keep track of the APIs and the docs, meanwhile general public can test out those collections by forking it in their personal workspace. Do take a look at it. Felt it will be useful for you guys.

Blog Post: [https://blog.postman.com/introducing-postman-public-workspaces/](https://blog.postman.com/introducing-postman-public-workspaces/)
Sample Workspace:[https://www.postman.com/postman/workspace/postman-public-workspace/overview]( https://www.postman.com/postman/workspace/postman-public-workspace/overview)

**Comment by 2pd** [comment]
thank you for the suggestion.

Because the collection requires API key/secret, which is extreme important to our users, we don't want to host it or have any dependency on other services.  For now, all collections are write in plain json file and fully open sourced, so it's easy to review by checking the commit history. Also the json files can be easily imported into other similar tools.

We are happy with current solution and will not have any change at this moment.

Thanks again.
