### ISSUE TITLE
Historical User Data

### ISSUE THREAD

**Issue by harryf98** [binance/binance-api-postman#95]
Hello,

I'm new to this API and I would like to know if someone knows how to get Historical User Data. I can't figure out how to get my Balance from a Week ago or a Month or  a Year, because If I know the amount of BTC I had I can calculate my profit at a given time.

Thanks in advance
Harry

**Comment by ishuen** [comment]
Hi.
I'm not sure what information you are looking for since balance and profit are two different concepts. But from this endpoint, you will get the account balance calculated in BTC on that day. https://binance-docs.github.io/apidocs/spot/en/#daily-account-snapshot-user_data

Btw, this question would be more suitable to raise in the forum. https://dev.binance.vision/
